language: java
before_install:
- chmod +x gradlew
script:
- gradle build
- cd petshelter-frontend/
- npm install
- yarn build
- cd ..
after_script:
- curl -s https://assertible.com/apis/4f4ff831-1846-4c84-84e0-53e94a80519a/run?api_token=U0bS1o6ELYFvuxaq
deploy:
- provider: heroku
  api_key: 03273874-ad50-428a-b7d2-d55ecd114926
  app: petshelter-backend
after_deploy:
- cd petshelter-frontend/
- deploy:
  - provider: heroku
    api_key: f10025c4-000a-4948-a036-6e5a016dec9c
    app: pet-pawlace
env:
  - TESTFOLDER=ca/mcgill/ecse321/petshelter/repository
  - TESTFOLDER=ca/mcgill/ecse321/petshelter/service
