matrix:
  include:
    - language: java
      install: true
      jdk:
        - oraclejdk8
      script:
        - ./gradlew build

    - language: node_js
      node_js:
        - 10.15
      before_install:
        - cd petshelter-frontend
      install:
        - npm install
		- set "SKIP_PREFLIGHT_CHECK=true"
      script:
        - yarn build
	after_script:
		- curl -s https://assertible.com/apis/4f4ff831-1846-4c84-84e0-53e94a80519a/run?api_token=U0bS1o6ELYFvuxaq
    - stage: deploy to backend app
      script: skip
      deploy:
        provider: heroku
        api_key: 03273874-ad50-428a-b7d2-d55ecd114926
        app: petshelter-backend

    - stage: deploy to frontend app
      script: skip
      deploy:
        provider: heroku
        api_key: 03273874-ad50-428a-b7d2-d55ecd114926
        app: pet-pawlace