matrix:
  include:
    - language: java
      script:
        - ./gradlew build

    - language: node_js
      node_js:
        - 10.15
      before_install:
        - cd petshelter-frontend
      install:
        - npm install
      script:
        - yarn build
    - stage: deploy to backend app
      script: skip
      deploy:
        provider: heroku
        api_key: 03273874-ad50-428a-b7d2-d55ecd114926
        app: petshelter-backend

    - stage: deploy to frontend app
      script: skip
      deploy:
        provider: heroku
        api_key: 03273874-ad50-428a-b7d2-d55ecd114926
        app: pet-pawlace
