language: java
before_install:
- chmod +x gradlew
install:
-npm install newman
script:
- gradle build
- newman run project-group-01/PetShelter-Backend/APItest/DonationAPI.json
deploy:
  provider: heroku
  api_key: 03273874-ad50-428a-b7d2-d55ecd114926
  app: petshelter-backend
env:
  - TESTFOLDER=ca/mcgill/ecse321/petshelter/repository
  - TESTFOLDER=ca/mcgill/ecse321/petshelter/service