language: java
before_install:
- chmod +x gradlew
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: "03273874-ad50-428a-b7d2-d55ecd114926"
  app: petshelter-backend
  on: project-group-01/master